### PR TITLE
Multiple outputs

### PR DESCRIPTION
**Pull request by ocefpaf**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ocefpaf** [comment]
https://github.com/conda-forge/admin-requests/pull/1228

**Review by dcherian — APPROVED** [review]
Thanks for doing this! What's the result of this change? (I'm confused since both outputs have the same name)

**Comment by ocefpaf** [comment]
> EDIT: I now see the - vs _. Is there a reason for this? It's only cf_xarray on pypi so I think it's nice to be consistent here

Try `pip install cf-xarray` and be amazed by the wonderful world of PyPI `-` and `_` mangling. In theory all Python packages in conda should have that to protect the namespace. B/c conda is python agnostic one can create a package named `cf-xarray` that is not `cf_xarray` and confuse pip users who rely on `-` instead of `_` (which are many b/c `-` doesn't require to press shift to type!).

**Comment by dcherian** [comment]
> Try pip install cf-xarray and be amazed by the wonderful world of PyPI - and _ mangling. 

🤦🏾‍♂️ 

Well thanks for taking this on! Please merge when you think its time to.

**Pull request merged**
